# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominioaldia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'ordering': ['alicuota']},
        ),
    ]
