# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioaldia_app', '0002_auto_20171026_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='demo_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cobranza_condominio',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='amount'),
        ),
    ]
