# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioaldia_app', '0003_auto_20171029_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_condominio',
            name='demo_mode',
            field=models.BooleanField(default=False, help_text='Determines if Condominium will be charged.'),
        ),
    ]
