# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioaldia_app', '0005_auto_20171108_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza_condominio_destinatario',
            name='deuda_inmueble',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='amount'),
        ),
    ]
